apiVersion: batch/v1
kind: Job
metadata:
  name: scanner
spec:
  template:
    spec:
      containers:
      - name: scanner
        image: ispeakcomputer/scanner:latest
        command: ["python3","test.py"]
        env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: app-tokens
              key: GITHUBTOKEN
        - name: REPOSITORY_LIST_URL
          valueFrom:
            secretKeyRef:
              name: app-tokens
              key: REPOSITORY_LIST_URL
      restartPolicy: Never
  backoffLimit: 4
