apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: bash
        command: ["sleep","1600"]
        env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: app-tokens
              key: GITHUBTOKEN
        - name: REPOSITORY_LIST_URL
          valueFrom:
            secretKeyRef:
              name: app-tokens
              key: REPOSITORY_LIST_URL
      restartPolicy: Never
  backoffLimit: 4
