apiVersion: v1
kind: Secret
metadata:
  name: app-tokens
data:
  GITHUBTOKEN: 
  REPOSITORY_LIST_URL: aHR0cHM6Ly9naXN0LmdpdGh1YnVzZXJjb250ZW50LmNvbS9qbWVsaXMvYzYwZTYxYTg5MzI0ODI0NGRjNGZhMTJiOTQ2NTg1YzQvcmF3LzI1ZDM5ZjY3ZjI0MDUzMzBhNjMxNGNhZDY0ZmFjNDIzYTE3MTE2MmMvc291cmNlcy50eHQ=





