apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: app-tokens
              key: GITHUBTOKEN
        - name: REPOSITORY_LIST_URL
          valueFrom:
            secretKeyRef:
              name: app-tokens
              key: REPOSITORY_LIST_URL
      restartPolicy: Never
  backoffLimit: 4
